### ISSUE TITLE
Write integration test as symfony bundle

### ISSUE THREAD

**Issue by yann-eugone** [yokai-php/batch-src#1]
Create a minimal symfony app in the integration test suite that uses the bundle.

**Comment by sachingk** [comment]
+1

**Comment by yann-eugone** [comment]
Something has already been done, issue wasn't closed, because I just forgot ^^

Please see PR https://github.com/yokai-php/batch-src/pull/49 or code at https://github.com/yokai-php/batch-src/tree/0.x/tests/symfony
