### ISSUE TITLE
Job execution is still running in AbstractDecoratedJob::postExecute()

### ISSUE THREAD

**Issue by Harry-Dunne** [yokai-php/batch-src#115]
### Description

Hi,

Not sure if it's a bug or a feature, but I'm confused by the status of a job in AbstractDecoratedJob::postExecute(). When this method is executed the decorated job is supposed to have failed or succeded but it's still marked as running. I use the Symfony bridge.

And I'm sure it's not a asynchronous execution for _yokai/batch-symfony-messenger_ and _yokai/batch-symfony-console_ are not installed so the launcher is a SimpleJobLauncher instance.

### Code

```php
<?php

namespace App\Job\Infocentre\N421;

use App\Repository\N421Repository;
use Yokai\Batch\Bridge\Symfony\Framework\JobWithStaticNameInterface;
use Yokai\Batch\Job\AbstractDecoratedJob;
use Yokai\Batch\Job\JobInterface;
use Yokai\Batch\JobExecution;
use Yokai\Batch\Warning;

class Job extends AbstractDecoratedJob implements JobWithStaticNameInterface
{

    public function __construct(private JobInterface $job, private N421Repository $repository)
    {
        parent::__construct($job);
    }

    /**
     * @inheritDoc
     */
    public static function getJobName(): string
    {
        return 'job.infocentre_grh.N421';
    }

    protected function preExecute(JobExecution $jobExecution): void
    {
        $connection = $this->repository->getConnection();
        $connection->beginTransaction();
    }

    protected function postExecute(JobExecution $jobExecution): void
    {
        $jobExecution->addWarning(new Warning($jobExecution->getStatus()->getValue())); // displays 2
        $connection = $this->repository->getConnection();
        if ($jobExecution->getStatus()->isUnsuccessful()) {
            $connection->rollBack();
        } else {
            $connection->commit();
        }
    }
}
```

**Comment by yann-eugone** [comment]
Hi @Harry-Dunne,
Thanks for reaching :slightly_smiling_face: 

The `AbstractDecoratedJob` on itself almost do nothing:
https://github.com/yokai-php/batch-src/blob/f6f6826036fa6e2166bc67576e9037e38714d909/src/batch/src/Job/AbstractDecoratedJob.php#L23-L25

The status switch is done by the `JobExecutor`:
- before running the job https://github.com/yokai-php/batch-src/blob/f6f6826036fa6e2166bc67576e9037e38714d909/src/batch/src/Job/JobExecutor.php#L56-L57
- after running the job https://github.com/yokai-php/batch-src/blob/f6f6826036fa6e2166bc67576e9037e38714d909/src/batch/src/Job/JobExecutor.php#L73-L74

But the `JobExecutor` is called:
- in the job launcher https://github.com/yokai-php/batch-src/blob/f6f6826036fa6e2166bc67576e9037e38714d909/src/batch/src/Launcher/SimpleJobLauncher.php#L26-L26
- or for each child job if your job is one of that type https://github.com/yokai-php/batch-src/blob/f6f6826036fa6e2166bc67576e9037e38714d909/src/batch/src/Job/JobWithChildJobs.php#L64-L64

So here, you are slightly to early for the status to have been updated

I can suggest few things that might help:
- make your own job decorator, try/catch the execution, and check whether failures were added to the JobExecution 
- subscribe to PreExecute & PostExecuteEvent

**Comment by Harry-Dunne** [comment]
Hi @yann-eugone 🙂 

Thanks for the quick reply!

I got it now. I just regret that there is a slight asymmetry: if the decorated job raises an exception, the jobException object returns the correct status (6) in postExecute(). But it's not a big deal, and the event dispatcher is a good advice.

BTW it's a great library, thanks for sharing!

**Comment by yann-eugone** [comment]
I'm glad you like it, this kind of comment is very appreciated :slightly_smiling_face: 

I understand your asymmetry point, this was not an issue before `JobExecutor` was introduced, because everything lied in the `AbstractJob` class
But I've always felt something was wrong about this, this is why a decided to move to `JobExecutor` : https://github.com/yokai-php/batch-src/pull/59

But I don't think `AbstractDecoratedJob` should use the `JobExecutor`, because it has been triggered by the `JobExecutor` in the first place...
