### ISSUE TITLE
Decouple the storage configuration command from the job launch commands

### ISSUE THREAD

**Issue by Harry-Dunne** [yokai-php/batch-src#118]
### Description

Hi,
I required **yokai-php/batch-symfony-console** to get the command to initialize my doctrine job execution storage.

There was a side effect: it activated the console job launcher provided by this bundle, and all my jobs became aynchronous which posed a problem for some of them. So, after my storage was setup, I had to remove the bundle from my dependencies.

This seems a bit tedious and a source of problems. Storage setup and job launchers are different concerns and should be bundled separatly.

**Comment by yann-eugone** [comment]
Hi,
Thanks for reporting

Yes, the bundle is trying to figure out by himself what is the most appropriate job launcher:
https://github.com/yokai-php/batch-src/blob/f6f6826036fa6e2166bc67576e9037e38714d909/src/batch-symfony-framework/src/DependencyInjection/YokaiBatchExtension.php#L66-L73

I thought it was a good idea in the first place, but I understand now that it was a mistake
That is why I created issues to help the developer regaining control over the configured launchers:
- https://github.com/yokai-php/batch-src/issues/92
- https://github.com/yokai-php/batch-src/issues/101

The idea in the end is to have a configuration that will look like messenger transports
Something like:
```yaml
yokai_batch:
  default_launcher: async
  launchers:
    simple: 'simple://simple'
    async: '%env(YOKAI_BATCH_ASYNC_LAUNCHER)%'
```

-------

But for the moment, you can change change the alias of the job launcher in your config:
```yaml
services:
  Yokai\Batch\Launcher\JobLauncherInterface: '@yokai_batch.job_launcher.simple'
```

**Comment by Harry-Dunne** [comment]
I like your DSN idea and your workaround solution suits me as it is. Anyway it's not a big deal. Thanks!
