### ISSUE TITLE
JobParameter for JobWithChildJobs

### ISSUE THREAD

**Issue by chemoul** [yokai-php/batch-src#69]
Hi,

Is there a way to get JobParameter from root job et give them automatically to child jobs?

In JobWithChildJobs.php, createChildExecution call could be `$jobExecution->createChildExecution($jobName, $jobExecution->getParameters())`.

**Comment by yann-eugone** [comment]
Hi @chemoul 🙂

For the moment, there is no way to do that.
I believe it's doable (it was I in my head), but I believe we might go on more work as intended:
How to provide child job parameters at start time for instance.

But while re-reading your description, you seems to just want to "copy" the value of the parent job's parameters to the child.
Why would you want that?
I mean, you can always access the parent job (and it's parent, and the parent of it's parent... until the root), and get parameters from it, no?

**Comment by chemoul** [comment]
Indeed, I need the copy the value for the parent job's parameters and it works by access to the parent job. 

Thank you @yann-eugone :+1:
